# Changelog

# ⚠⚠ Please follow the format provided ⚠⚠
#  - name: version number
#    changes:
#      - title: Title of changes
#        categories: [CHANGED AREA]
#        authors: [YourName]


releases:
  - name: 1.4.2
    changes:
      - title: Update API Client
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.4.0
    changes:
      - title: Change Discord Support Url
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Add Dependency Check for Steam and OneStore
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Update Packages and fixes minor bugs
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.6
    changes:
      - title: Change GitHub Release Type for Pre-Release Builds
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.5
    changes:
      - title: Remove GitHub Issue Button
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.4
    changes:
      - title: Add GitHub Release Type for Staging Builds
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.3
    changes:
      - title: Add Scrollbar to Addon List
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.2
    changes:
      - title: Fixes CDN
        categories: [ Infrastructure ]
        authors: [ Revyn112 ]
  - name: 1.3.0
    changes:
      - title: Updated to latest FBW Installer Code
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Added local assets
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Added GitHub Actions
        categories: [ Logic ]
        authors: [ Revyn112 ]
  - name: 1.2.0
    changes:
      - title: Updated to latest FBW Installer Code
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.1.0
    changes:
      - title: Updated to latest FBW Installer Code
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.0.0
    changes:
      - title: Initial Release
        authors: [ Revyn112 ]